#!/bin/bash
# Test AI Render Pipeline with B-roll generation
# Requires OPENROUTER_API_KEY to be set in the environment

BASE_URL="${VIBEE_URL:-https://vibee-mcp.fly.dev}"

echo "Testing AI Render Pipeline at: $BASE_URL"
echo ""

# Test request with script text
curl -s -X POST "$BASE_URL/api/video/ai-render" \
  -H "Content-Type: application/json" \
  -d '{
    "photo_url": "https://example.com/photo.jpg",
    "script_text": "Welcome to our business presentation. Today we will discuss the latest market trends and how technology is transforming the way we work. Our team has developed innovative solutions that help companies grow.",
    "test_mode": true
  }' | jq .

echo ""
echo "If successful, you should see broll_prompts generated by AI"
